version: "3.7"

services:

  voting-challenge-db:
    image: mysql:8.0.29
    container_name: voting-challenge-db
    hostname: voting-challenge-db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_USER: docker
      MYSQL_PASSWORD: admin123
      MYSQL_DATABASE: voting-challenge
      MYSQL_ROOT_HOST: "%"
      MYSQL_TCP_PORT: 3310
    ports:
      - "3310:3310"
    networks:
      - voting-challenge-network

  voting-challenge:
    image: fmatheus21/voting-challenge
    container_name: voting-challenge
    hostname: voting-challenge
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      TZ: America/Sao_Paulo
      SPRING.APPLICATION.NAME: authorization-server
      SPRING.DATASOURCE.URL: jdbc:mysql://voting-challenge-db:3310/voting-challenge?useSSL=false&useTimezone=true&serverTimezone=America/Sao_Paulo&enabledTLSProtocols=TLSv1.2
      SPRING.DATASOURCE.USERNAME: docker
      SPRING.DATASOURCE.PASSWORD: admin123
      SPRING.FLYWAY.URL: jdbc:mysql://voting-challenge-db:3310/voting-challenge?useSSL=false&useTimezone=true&serverTimezone=America/Sao_Paulo&enabledTLSProtocols=TLSv1.2
      SPRING.FLYWAY.USER: docker
      SPRING.FLYWAY.PASSWORD: admin123
      SPRING.JPA.SHOWSQL: "false"
      SERVER.PORT: "8100"
    ports:
      - "8100:8100"
    depends_on:
      - voting-challenge-db
    networks:
      - voting-challenge-network
networks:
  voting-challenge-network:
    driver: bridge